---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ApplicationProcessing
  labels:
    app: ApplicationProcessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ApplicationProcessing
  template:
    metadata:
      labels:
        app: ApplicationProcessing
    spec:
      containers:
        - name: ApplicationProcessing
          image: username/ApplicationProcessing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DataCollection
  labels:
    app: DataCollection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DataCollection
  template:
    metadata:
      labels:
        app: DataCollection
    spec:
      containers:
        - name: DataCollection
          image: username/DataCollection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentIssuance
  labels:
    app: DocumentIssuance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentIssuance
  template:
    metadata:
      labels:
        app: DocumentIssuance
    spec:
      containers:
        - name: DocumentIssuance
          image: username/DocumentIssuance:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ApplicationProcessing
  labels:
    app: ApplicationProcessing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ApplicationProcessing


---


apiVersion: v1
kind: Service
metadata:
  name: DataCollection
  labels:
    app: DataCollection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DataCollection


---


apiVersion: v1
kind: Service
metadata:
  name: DocumentIssuance
  labels:
    app: DocumentIssuance
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DocumentIssuance

